#!/usr/bin/env bash
# This script displays Best School ten time by using the 'while' loop

# Initialize the variable 'counter' to 1
counter=1

# Runs the while loop as long as the value of 'counter' is less than or equal to zero
while [ $counter -le 10 ]
do

# Prints the string 'Best School' for every iteration of the while loop
    echo "Best School"

# Increment the counter until the last iteration
    ((counter++))
done
