#!/usr/bin/env bash
# This script loops from 1 to 10 and displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations.

# Initialize the counter to 1

counter=1

# Runs a while loop as long as counter is less than or equal to 10

while [ $counter -le 10 ]

do

# Displays 'bad luck' if the counter is equal to 4

    if [ $counter -eq 4 ]; then
        echo "bad luck"
# Displays 'good luck' if the counter is equal to 8

    elif [ $counter -eq 8 ]; then
        echo "good luck"

# Displays 'Best School' when the counter does not satisfy either conditions above

    else
        echo "Best School"

# Closes the 'if' loop.

    fi

# Increments the counter after each succesful loop by 1
    ((counter++))
done
