#!/usr/bin/env bash
#This script displays content of the current directory in a list format and the part of the name afte the first dash is deisplayed,


# Loop through files in the current directory
for file in *; do
    # Check if the file is not hidden and is a regular file
    if [[ ! $file == .* ]] && [[ -f $file ]]; then
        # Extract the part of the name after the first dash
        name=${file#*-}

        # Display the modified name
        echo "$name"
    fi
done
