#!/usr/bin/env bash
# This script displays list of currently running processes
# Shows all processes, for all users, including those which might not have a TTY
# Displays in user-oriented format
# Shows process hierarchy

ps -a -x -u -f

