#!/usr/bin/env bash
# Init script to manage the execution of manage_my_process
case $1 in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process already started."
    else
      echo $$ > /var/run/my_process.pid
      echo "manage_my_process started."
      /path/to/manage_my_process start
    fi
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
      /path/to/manage_my_process stop
    else
      echo "manage_my_process already stopped."
    fi
    ;;
  restart)
    $0 stop
    $0 start
    echo "manage_my_process restarted."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac


