#!/usr/bin/env bash
# Init script to manage the execution of manage_my_process

# Check if the process is already running
check_process_running() {
  if [ -f /var/run/my_process.pid ]; then
    pid=$(cat /var/run/my_process.pid)
    if ps -p "$pid" > /dev/null; then
      return 0  # Process is running
    else
      rm /var/run/my_process.pid
    fi
  fi
  return 1  # Process is not running
}

case $1 in
  start)
    if check_process_running; then
      echo "manage_my_process already started."
    else
      echo $$ > /var/run/my_process.pid
      echo "manage_my_process started."
      /alu-shell/processes_and_signals/manage_my_process start
    fi
    ;;
  stop)
    if check_process_running; then
      pid=$(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
      /alu-shell/processes_and_signals/manage_my_process stop
    else
      echo "manage_my_process already stopped."
    fi
    ;;
  restart)
    if check_process_running; then
      $0 stop
    fi
    $0 start
    echo "manage_my_process restarted."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac

