#!/usr/bin/env bash
# Bash script to manage the execution of manage_my_process.sh
case $1 in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process already started."
    else
      echo $$ > /var/run/my_process.pid
      echo "manage_my_process started."
      while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
      done
    fi
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      pid=$(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
      kill -9 $pid
    else
      echo "manage_my_process already stopped."
    fi
    ;;
  restart)
    $0 stop
    $0 start
    echo "manage_my_process restarted."
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac

