#!/usr/bin/env bash
# Bash script to manage the execution of manage_my_process.sh
case $1 in
  start)
    if [[ -f /var/run/my_process.pid ]]; then
      echo "manage_my_process is already started."
      exit 1
    fi
    
    ./manage_my_process.sh &
    pid=$!
    echo $pid > /var/run/my_process.pid
    echo "manage_my_process started."
    ;;
    
  stop)
    if [[ ! -f /var/run/my_process.pid ]]; then
      echo "manage_my_process is not running."
      exit 1
    fi
    
    pid=$(cat /var/run/my_process.pid)
    kill $pid
    rm /var/run/my_process.pid
    echo "manage_my_process stopped."
    ;;
    
  restart)
    if [[ -f /var/run/my_process.pid ]]; then
      pid=$(cat /var/run/my_process.pid)
      kill $pid
      rm /var/run/my_process.pid
      echo "manage_my_process stopped."
    fi
    
    ./manage_my_process.sh &
    pid=$!
    echo $pid > /var/run/my_process.pid
    echo "manage_my_process restarted."
    ;;
    
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

